spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/slotgame?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    initialization-mode: always
    # username and password are passed via environment variables
  sql:
    init:
      mode: always
      data-locations:
        - classpath:insert_symbols.sql
        - classpath:insert_slots_reels.sql
        - classpath:insert_coordinates.sql
        - classpath:insert_paylines.sql
        - classpath:insert_payouts.sql
